// demo/vue/src/App.vue
<template>
  <div class="app">
    <div class="toolbar">
      <b class="brand">pretext-editor</b>
      <span class="tag">Vue Demo</span>

      <label class="ctrl-label">
        Language:
        <select v-model="language" class="ctrl-select">
          <option v-for="lang in LANGUAGES" :key="lang.value" :value="lang.value">{{ lang.label }}</option>
        </select>
      </label>

      <label class="ctrl-label">
        Theme:
        <select v-model="theme" class="ctrl-select">
          <option value="dark-plus">Dark+ (VS Code)</option>
          <option value="dracula">Dracula</option>
          <option value="github-light">GitHub Light</option>
        </select>
      </label>

      <label class="ctrl-label">
        Font size:
        <select v-model.number="fontSize" class="ctrl-select ctrl-select--narrow">
          <option v-for="n in fontSizeOptions" :key="n" :value="n">{{ n }}</option>
        </select>
      </label>

      <button class="btn" @click="openFile">Open File</button>
      <button class="btn" :class="{ 'btn--active': wordWrap }" @click="wordWrap = !wordWrap">换行</button>
      <input ref="fileInputRef" type="file" class="file-input-hidden" @change="onFileChange" />
    </div>

    <div class="editor-wrap">
      <PretextEditor
        ref="editorRef"
        :value="code"
        @update:value="code = $event"
        @cursor-change="cursor = $event"
        :language="language"
        :font-size="fontSize"
        :tab-size="tabSize"
        :theme="theme"
        :word-wrap="wordWrap"
      />
    </div>

    <div class="statusbar">
      <span>行 {{ cursor.line + 1 }}, 列 {{ cursor.col + 1 }}</span>
      <span>Tab Size: {{ tabSize }}</span>
      <span>UTF-8</span>
      <span>{{ LANGUAGES.find(l => l.value === language)?.label ?? language }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { PretextEditor } from 'pretext-editor/vue'
import type { PretextEditorHandle } from 'pretext-editor/vue'

const LANGUAGES = [
  { value: 'c',           label: 'C' },
  { value: 'cpp',         label: 'C++' },
  { value: 'csharp',      label: 'C#' },
  { value: 'css',         label: 'CSS' },
  { value: 'dart',        label: 'Dart' },
  { value: 'fish',        label: 'Fish' },
  { value: 'glsl',        label: 'GLSL' },
  { value: 'go',          label: 'Go' },
  { value: 'graphql',     label: 'GraphQL' },
  { value: 'haml',        label: 'Haml' },
  { value: 'html',        label: 'HTML' },
  { value: 'java',        label: 'Java' },
  { value: 'javascript',  label: 'JavaScript' },
  { value: 'json',        label: 'JSON' },
  { value: 'jsonc',       label: 'JSONC' },
  { value: 'jsx',         label: 'JSX' },
  { value: 'kotlin',      label: 'Kotlin' },
  { value: 'less',        label: 'Less' },
  { value: 'lua',         label: 'Lua' },
  { value: 'markdown',    label: 'Markdown' },
  { value: 'php',         label: 'PHP' },
  { value: 'postcss',     label: 'PostCSS' },
  { value: 'python',      label: 'Python' },
  { value: 'r',           label: 'R' },
  { value: 'ruby',        label: 'Ruby' },
  { value: 'rust',        label: 'Rust' },
  { value: 'scala',       label: 'Scala' },
  { value: 'scss',        label: 'SCSS' },
  { value: 'shellscript', label: 'Shell Script' },
  { value: 'sql',         label: 'SQL' },
  { value: 'svelte',      label: 'Svelte' },
  { value: 'swift',       label: 'Swift' },
  { value: 'toml',        label: 'TOML' },
  { value: 'tsx',         label: 'TSX' },
  { value: 'typescript',  label: 'TypeScript' },
  { value: 'vue',         label: 'Vue' },
  { value: 'xml',         label: 'XML' },
  { value: 'yaml',        label: 'YAML' },
]

const EXT_TO_LANG: Record<string, string> = {
  ts: 'typescript', tsx: 'tsx',
  js: 'javascript', jsx: 'jsx',
  py: 'python',
  rs: 'rust',
  go: 'go',
  c: 'c', h: 'c',
  cpp: 'cpp', cc: 'cpp', cxx: 'cpp', hpp: 'cpp',
  cs: 'csharp',
  java: 'java',
  kt: 'kotlin',
  swift: 'swift',
  css: 'css',
  html: 'html', htm: 'html',
  xml: 'xml',
  graphql: 'graphql', gql: 'graphql',
  sh: 'shellscript', bash: 'shellscript', zsh: 'shellscript', fish: 'fish',
  lua: 'lua',
  yaml: 'yaml', yml: 'yaml',
  rb: 'ruby',
  json: 'json',
  jsonc: 'jsonc',
  php: 'php',
  r: 'r',
  dart: 'dart',
  scala: 'scala',
  scss: 'scss',
  less: 'less',
  vue: 'vue',
  svelte: 'svelte',
  toml: 'toml',
  md: 'markdown', mdx: 'markdown',
  sql: 'sql',
  haml: 'haml',
  glsl: 'glsl', vert: 'glsl', frag: 'glsl',
}

const SAMPLE_CODE = `function fibonacci(n: number): number {
  if (n <= 1) return n
  return fibonacci(n - 1) + fibonacci(n - 2)
}

// Test it
for (let i = 0; i < 10; i++) {
  console.log(\`fib(\${i}) = \${fibonacci(i)}\`)
}
`

const code = ref(SAMPLE_CODE)
const language = ref('typescript')
const theme = ref('dark-plus')
const fontSize = ref(14)
const tabSize = ref(4)
const wordWrap = ref(false)
const cursor = ref({ line: 0, col: 0 })
const editorRef = ref<PretextEditorHandle>()
const fileInputRef = ref<HTMLInputElement>()

const fontSizeOptions = computed(() => {
  const opts = []
  for (let n = 5; n <= 40; n += 2) opts.push(n)
  return opts
})

function openFile() {
  fileInputRef.value?.click()
}

function onFileChange(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0]
  if (!file) return
  const ext = file.name.split('.').pop()?.toLowerCase() ?? ''
  const detected = EXT_TO_LANG[ext]
  if (detected) language.value = detected
  const reader = new FileReader()
  reader.onload = () => { code.value = reader.result as string }
  reader.readAsText(file)
  ;(e.target as HTMLInputElement).value = ''
}
</script>

<style scoped>
.app { height: 100%; display: flex; flex-direction: column; }
.toolbar {
  display: flex; align-items: center; gap: 12px; flex-wrap: wrap;
  padding: 8px 16px; background: #252526;
  border-bottom: 1px solid #333; font-size: 13px; flex-shrink: 0;
}
.brand { color: #0098ff; }
.tag { color: #888; }
.ctrl-label { display: flex; align-items: center; gap: 6px; color: #ccc; }
.ctrl-label:first-of-type { margin-left: auto; }
.ctrl-select {
  background: #3c3c3c; color: #ccc; border: 1px solid #555;
  border-radius: 4px; padding: 4px 8px; font-size: 13px;
}
.ctrl-select--narrow { width: 64px; }
.btn {
  background: #0e639c; color: #fff; border: none;
  border-radius: 4px; padding: 4px 12px; font-size: 13px; cursor: pointer;
}
.btn--active { background: #1177bb; outline: 1px solid #4fc3f7; }
.editor-wrap { flex: 1; overflow: hidden; }
.file-input-hidden { display: none; }
.statusbar {
  display: flex; gap: 16px; align-items: center;
  padding: 2px 16px; background: #007acc; color: #fff;
  font-size: 12px; flex-shrink: 0; user-select: none;
}
</style>

// demo/react/src/App.tsx
import React, { useState, useCallback, useRef } from 'react'
import { PretextEditor } from 'pretext-editor/react'
import type { PretextEditorHandle } from 'pretext-editor/react'

const LANGUAGES = [
  { value: 'c',           label: 'C' },
  { value: 'cpp',         label: 'C++' },
  { value: 'csharp',      label: 'C#' },
  { value: 'css',         label: 'CSS' },
  { value: 'dart',        label: 'Dart' },
  { value: 'fish',        label: 'Fish' },
  { value: 'glsl',        label: 'GLSL' },
  { value: 'go',          label: 'Go' },
  { value: 'graphql',     label: 'GraphQL' },
  { value: 'haml',        label: 'Haml' },
  { value: 'html',        label: 'HTML' },
  { value: 'java',        label: 'Java' },
  { value: 'javascript',  label: 'JavaScript' },
  { value: 'json',        label: 'JSON' },
  { value: 'jsonc',       label: 'JSONC' },
  { value: 'jsx',         label: 'JSX' },
  { value: 'kotlin',      label: 'Kotlin' },
  { value: 'less',        label: 'Less' },
  { value: 'lua',         label: 'Lua' },
  { value: 'markdown',    label: 'Markdown' },
  { value: 'php',         label: 'PHP' },
  { value: 'postcss',     label: 'PostCSS' },
  { value: 'python',      label: 'Python' },
  { value: 'r',           label: 'R' },
  { value: 'ruby',        label: 'Ruby' },
  { value: 'rust',        label: 'Rust' },
  { value: 'scala',       label: 'Scala' },
  { value: 'scss',        label: 'SCSS' },
  { value: 'shellscript', label: 'Shell Script' },
  { value: 'sql',         label: 'SQL' },
  { value: 'svelte',      label: 'Svelte' },
  { value: 'swift',       label: 'Swift' },
  { value: 'toml',        label: 'TOML' },
  { value: 'tsx',         label: 'TSX' },
  { value: 'typescript',  label: 'TypeScript' },
  { value: 'vue',         label: 'Vue' },
  { value: 'xml',         label: 'XML' },
  { value: 'yaml',        label: 'YAML' },
]

const EXT_TO_LANG: Record<string, string> = {
  ts: 'typescript', tsx: 'tsx',
  js: 'javascript', jsx: 'jsx',
  py: 'python', rs: 'rust', go: 'go',
  c: 'c', h: 'c', cpp: 'cpp', cc: 'cpp', cxx: 'cpp', hpp: 'cpp',
  cs: 'csharp', java: 'java', kt: 'kotlin', swift: 'swift',
  css: 'css', html: 'html', htm: 'html', xml: 'xml',
  graphql: 'graphql', gql: 'graphql',
  sh: 'shellscript', bash: 'shellscript', zsh: 'shellscript', fish: 'fish',
  lua: 'lua', yaml: 'yaml', yml: 'yaml', rb: 'ruby',
  json: 'json', jsonc: 'jsonc', php: 'php', r: 'r', dart: 'dart',
  scala: 'scala', scss: 'scss', less: 'less',
  vue: 'vue', svelte: 'svelte', toml: 'toml',
  md: 'markdown', mdx: 'markdown', sql: 'sql',
  haml: 'haml', glsl: 'glsl', vert: 'glsl', frag: 'glsl',
}

const SAMPLE_CODE = `function fibonacci(n: number): number {
  if (n <= 1) return n
  return fibonacci(n - 1) + fibonacci(n - 2)
}

// Test it
for (let i = 0; i < 10; i++) {
  console.log(\`fib(\${i}) = \${fibonacci(i)}\`)
}
`

const FONT_SIZE_OPTIONS: number[] = []
for (let n = 5; n <= 40; n += 2) FONT_SIZE_OPTIONS.push(n)

export default function App() {
  const [code, setCode] = useState(SAMPLE_CODE)
  const [language, setLanguage] = useState('typescript')
  const [theme, setTheme] = useState('dark-plus')
  const [fontSize, setFontSize] = useState(14)
  const [tabSize] = useState(4)
  const [wordWrap, setWordWrap] = useState(false)
  const [cursor, setCursor] = useState({ line: 0, col: 0 })
  const editorRef = useRef<PretextEditorHandle>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const handleChange = useCallback((value: string) => setCode(value), [])

  function openFile() { fileInputRef.current?.click() }

  function onFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    const ext = file.name.split('.').pop()?.toLowerCase() ?? ''
    const detected = EXT_TO_LANG[ext]
    if (detected) setLanguage(detected)
    const reader = new FileReader()
    reader.onload = () => setCode(reader.result as string)
    reader.readAsText(file)
    e.target.value = ''
  }

  const sel: React.CSSProperties = {
    background: '#3c3c3c', color: '#ccc', border: '1px solid #555',
    borderRadius: 4, padding: '4px 8px', fontSize: 13,
  }

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      <div style={{
        display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap',
        padding: '8px 16px', background: '#252526',
        borderBottom: '1px solid #333', fontSize: 13, flexShrink: 0,
      }}>
        <b style={{ color: '#0098ff' }}>pretext-editor</b>
        <span style={{ color: '#888' }}>React Demo</span>

        <label style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 6, color: '#ccc' }}>
          Language:
          <select value={language} onChange={e => setLanguage(e.target.value)} style={sel}>
            {LANGUAGES.map(l => <option key={l.value} value={l.value}>{l.label}</option>)}
          </select>
        </label>

        <label style={{ display: 'flex', alignItems: 'center', gap: 6, color: '#ccc' }}>
          Theme:
          <select value={theme} onChange={e => setTheme(e.target.value)} style={sel}>
            <option value="dark-plus">Dark+ (VS Code)</option>
            <option value="dracula">Dracula</option>
            <option value="github-light">GitHub Light</option>
          </select>
        </label>

        <label style={{ display: 'flex', alignItems: 'center', gap: 6, color: '#ccc' }}>
          Font size:
          <select value={fontSize} onChange={e => setFontSize(Number(e.target.value))} style={{ ...sel, width: 64 }}>
            {FONT_SIZE_OPTIONS.map(n => <option key={n} value={n}>{n}</option>)}
          </select>
        </label>

        <button onClick={openFile} style={{ background: '#0e639c', color: '#fff', border: 'none', borderRadius: 4, padding: '4px 12px', fontSize: 13, cursor: 'pointer' }}>
          Open File
        </button>
        <button
          onClick={() => setWordWrap(w => !w)}
          style={{ background: wordWrap ? '#1177bb' : '#0e639c', color: '#fff', border: 'none', outline: wordWrap ? '1px solid #4fc3f7' : 'none', borderRadius: 4, padding: '4px 12px', fontSize: 13, cursor: 'pointer' }}
        >
          换行
        </button>
        <input ref={fileInputRef} type="file" style={{ display: 'none' }} onChange={onFileChange} />
      </div>

      <div style={{ flex: 1, overflow: 'hidden' }}>
        <PretextEditor
          ref={editorRef}
          value={code}
          onChange={handleChange}
          onCursorChange={setCursor}
          language={language}
          fontSize={fontSize}
          tabSize={tabSize}
          theme={theme}
          wordWrap={wordWrap}
        />
      </div>

      <div style={{
        display: 'flex', gap: 16, alignItems: 'center',
        padding: '2px 16px', background: '#007acc', color: '#fff',
        fontSize: 12, flexShrink: 0, userSelect: 'none',
      }}>
        <span>行 {cursor.line + 1}, 列 {cursor.col + 1}</span>
        <span>Tab Size: {tabSize}</span>
        <span>UTF-8</span>
        <span>{LANGUAGES.find(l => l.value === language)?.label ?? language}</span>
      </div>
    </div>
  )
}
